<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>comm_test</name>
  <version>0.0.0</version>
  <description>独立节点，单独验证 shared_package 的 Communication_Interface + USB_CDC 这一层的收发，不经过 ros2_control。</description>
  <maintainer email="carbon@todo.todo">carbon</maintainer>
  <license>Apache-2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>

  <depend>rclcpp</depend>
  <depend>shared_package</depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
